<?xml version="1.0" encoding="utf-8"?><Database Name="dbMoviebase" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PRD;Initial Catalog=dbMoviebase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbMoviebaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAdmins" Member="tblAdmins">
    <Type Name="tblAdmin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Storage="_password" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblMovies" Member="tblMovies">
    <Type Name="tblMovies">
      <Column Name="movie_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="movie_name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="genre_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_by" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="movie_year" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="movie_description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="review" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="director" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="image_location" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>