#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbMoviebase")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblAdmin(tblAdmin instance);
  partial void UpdatetblAdmin(tblAdmin instance);
  partial void DeletetblAdmin(tblAdmin instance);
  partial void InserttblMovies(tblMovies instance);
  partial void UpdatetblMovies(tblMovies instance);
  partial void DeletetblMovies(tblMovies instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbMoviebaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblAdmin> tblAdmins
	{
		get
		{
			return this.GetTable<tblAdmin>();
		}
	}
	
	public System.Data.Linq.Table<tblMovies> tblMovies
	{
		get
		{
			return this.GetTable<tblMovies>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAdmins")]
public partial class tblAdmin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _username;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
	
	public tblAdmin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string pass
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpassChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("pass");
				this.OnpassChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMovies")]
public partial class tblMovies : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _movie_ID;
	
	private string _movie_name;
	
	private int _genre_ID;
	
	private System.DateTime _created_date;
	
	private string _created_by;
	
	private string _movie_year;
	
	private string _movie_description;
	
	private string _review;
	
	private string _director;
	
	private string _image_location;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmovie_IDChanging(int value);
    partial void Onmovie_IDChanged();
    partial void Onmovie_nameChanging(string value);
    partial void Onmovie_nameChanged();
    partial void Ongenre_IDChanging(int value);
    partial void Ongenre_IDChanged();
    partial void Oncreated_dateChanging(System.DateTime value);
    partial void Oncreated_dateChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Onmovie_yearChanging(string value);
    partial void Onmovie_yearChanged();
    partial void Onmovie_descriptionChanging(string value);
    partial void Onmovie_descriptionChanged();
    partial void OnreviewChanging(string value);
    partial void OnreviewChanged();
    partial void OndirectorChanging(string value);
    partial void OndirectorChanged();
    partial void Onimage_locationChanging(string value);
    partial void Onimage_locationChanged();
    #endregion
	
	public tblMovies()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movie_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int movie_ID
	{
		get
		{
			return this._movie_ID;
		}
		set
		{
			if ((this._movie_ID != value))
			{
				this.Onmovie_IDChanging(value);
				this.SendPropertyChanging();
				this._movie_ID = value;
				this.SendPropertyChanged("movie_ID");
				this.Onmovie_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movie_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string movie_name
	{
		get
		{
			return this._movie_name;
		}
		set
		{
			if ((this._movie_name != value))
			{
				this.Onmovie_nameChanging(value);
				this.SendPropertyChanging();
				this._movie_name = value;
				this.SendPropertyChanged("movie_name");
				this.Onmovie_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre_ID", DbType="Int NOT NULL")]
	public int genre_ID
	{
		get
		{
			return this._genre_ID;
		}
		set
		{
			if ((this._genre_ID != value))
			{
				this.Ongenre_IDChanging(value);
				this.SendPropertyChanging();
				this._genre_ID = value;
				this.SendPropertyChanged("genre_ID");
				this.Ongenre_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime NOT NULL")]
	public System.DateTime created_date
	{
		get
		{
			return this._created_date;
		}
		set
		{
			if ((this._created_date != value))
			{
				this.Oncreated_dateChanging(value);
				this.SendPropertyChanging();
				this._created_date = value;
				this.SendPropertyChanged("created_date");
				this.Oncreated_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string created_by
	{
		get
		{
			return this._created_by;
		}
		set
		{
			if ((this._created_by != value))
			{
				this.Oncreated_byChanging(value);
				this.SendPropertyChanging();
				this._created_by = value;
				this.SendPropertyChanged("created_by");
				this.Oncreated_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movie_year", DbType="VarChar(50)")]
	public string movie_year
	{
		get
		{
			return this._movie_year;
		}
		set
		{
			if ((this._movie_year != value))
			{
				this.Onmovie_yearChanging(value);
				this.SendPropertyChanging();
				this._movie_year = value;
				this.SendPropertyChanged("movie_year");
				this.Onmovie_yearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movie_description", DbType="VarChar(MAX)")]
	public string movie_description
	{
		get
		{
			return this._movie_description;
		}
		set
		{
			if ((this._movie_description != value))
			{
				this.Onmovie_descriptionChanging(value);
				this.SendPropertyChanging();
				this._movie_description = value;
				this.SendPropertyChanged("movie_description");
				this.Onmovie_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_review", DbType="VarChar(50)")]
	public string review
	{
		get
		{
			return this._review;
		}
		set
		{
			if ((this._review != value))
			{
				this.OnreviewChanging(value);
				this.SendPropertyChanging();
				this._review = value;
				this.SendPropertyChanged("review");
				this.OnreviewChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_director", DbType="VarChar(150)")]
	public string director
	{
		get
		{
			return this._director;
		}
		set
		{
			if ((this._director != value))
			{
				this.OndirectorChanging(value);
				this.SendPropertyChanging();
				this._director = value;
				this.SendPropertyChanged("director");
				this.OndirectorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_location", DbType="VarChar(200)")]
	public string image_location
	{
		get
		{
			return this._image_location;
		}
		set
		{
			if ((this._image_location != value))
			{
				this.Onimage_locationChanging(value);
				this.SendPropertyChanging();
				this._image_location = value;
				this.SendPropertyChanged("image_location");
				this.Onimage_locationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
